---
services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/bencrane/n8n-on-render
    branch: main
    plan: starter
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_HOST
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: N8N_ENCRYPTION_KEY
        sync: false
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        sync: false
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        sync: false
      - key: DB_POSTGRESDB_USER
        sync: false
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
